version: '3'

services:
  cockroachdb:
    image: cockroachdb/cockroach:v22.2.14
    ports:
      - 26257:26257
      - 8080:8080
    environment:
      - COCKROACH_DATABASE=app
      - COCKROACH_USER=root
    volumes:
      - cockroach-volume:/cockroach/cockroach-data
    command: start-single-node --insecure

volumes:
  cockroach-volume:
